In [59]:
import cv2
import numpy as np

In [60]:
#Loading image
image = cv2.imread('Images/image1.jpg', cv2.IMREAD_COLOR)

In [61]:
#Creating a line on the image
cv2.line(image, (0,0), (150,150), (255,255,255), 15) #cv2.line(image_object, initial point, final point, color_value, line_width) #creates a line of specified arguments

#Color values in cv2 are of the format BGR, thus basic values can be dispalyed using:

#Color  : #Value
#=====    ======

#Black  : 0,0,0
#Red    : 0,0,255
#Blue   : 255,0,0
#Green  : 0,255,0
#Yellow : 0,255,255
#Cyan   : 255,0,255
#Indigo : 255,255,0

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [245, 252, 255],
        [239, 248, 252],
        [233, 242, 246]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [244, 255, 255],
        [240, 251, 255],
        [223, 235, 239]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [194, 212, 213],
        [209, 228, 231],
        [204, 223, 226]],

       ...,

       [[ 57,  63,  68],
        [ 54,  60,  65],
        [ 50,  56,  61],
        ...,
        [138, 137, 139],
        [118, 120, 120],
        [113, 115, 115]],

       [[ 57,  63,  68],
        [ 55,  61,  66],
        [ 52,  58,  63],
        ...,
        [144, 143, 145],
        [127, 129, 129],
        [123, 125, 125]],

       [[ 58,  64,  69],
        [ 57,  63,  68],
        [ 55,  61,  66],
        ...,
        [145, 144, 146],
        [139, 141, 141],
        [142, 144, 144]]

In [62]:
#Displaying the image
cv2.imshow('Image Window', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
#Loading image
image = cv2.imread('Images/image1.jpg', cv2.IMREAD_COLOR)

#Suppose we want to draw a rectangle then:
cv2.rectangle(image, (100,200), (250,350), (0,255,0), 5)
#cv2.rectangle(image_obj, top_left coordinate, bottom_right_coordinate, color_value, line_width)

array([[[ 49,  76,  73],
        [ 40,  67,  64],
        [ 30,  57,  53],
        ...,
        [245, 252, 255],
        [239, 248, 252],
        [233, 242, 246]],

       [[ 43,  70,  67],
        [ 36,  63,  60],
        [ 29,  56,  53],
        ...,
        [244, 255, 255],
        [240, 251, 255],
        [223, 235, 239]],

       [[ 39,  67,  67],
        [ 37,  66,  63],
        [ 34,  63,  60],
        ...,
        [194, 212, 213],
        [209, 228, 231],
        [204, 223, 226]],

       ...,

       [[ 57,  63,  68],
        [ 54,  60,  65],
        [ 50,  56,  61],
        ...,
        [138, 137, 139],
        [118, 120, 120],
        [113, 115, 115]],

       [[ 57,  63,  68],
        [ 55,  61,  66],
        [ 52,  58,  63],
        ...,
        [144, 143, 145],
        [127, 129, 129],
        [123, 125, 125]],

       [[ 58,  64,  69],
        [ 57,  63,  68],
        [ 55,  61,  66],
        ...,
        [145, 144, 146],
        [139, 141, 141],
        [142, 144, 144]]

In [64]:
#Dispaying the image
cv2.imshow('Image Window', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
#Loading image
image = cv2.imread('Images/image1.jpg', cv2.IMREAD_COLOR)

#Suppose we want to draw a circle on the image
cv2.circle(image, (350,100) , 75, (0,0,255), -12)
#cv2.circle(image_obj, coordinate of center, radius of circle, linewidth) #Creates a circle for the passed specs

#If we pass negative line width, that means that line width is not present that is alternatively the circle will be filled

array([[[ 49,  76,  73],
        [ 40,  67,  64],
        [ 30,  57,  53],
        ...,
        [245, 252, 255],
        [239, 248, 252],
        [233, 242, 246]],

       [[ 43,  70,  67],
        [ 36,  63,  60],
        [ 29,  56,  53],
        ...,
        [244, 255, 255],
        [240, 251, 255],
        [223, 235, 239]],

       [[ 39,  67,  67],
        [ 37,  66,  63],
        [ 34,  63,  60],
        ...,
        [194, 212, 213],
        [209, 228, 231],
        [204, 223, 226]],

       ...,

       [[ 57,  63,  68],
        [ 54,  60,  65],
        [ 50,  56,  61],
        ...,
        [138, 137, 139],
        [118, 120, 120],
        [113, 115, 115]],

       [[ 57,  63,  68],
        [ 55,  61,  66],
        [ 52,  58,  63],
        ...,
        [144, 143, 145],
        [127, 129, 129],
        [123, 125, 125]],

       [[ 58,  64,  69],
        [ 57,  63,  68],
        [ 55,  61,  66],
        ...,
        [145, 144, 146],
        [139, 141, 141],
        [142, 144, 144]]

In [66]:
#Displaying the image
cv2.imshow('Image Window', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [67]:
#Loading image
image = cv2.imread('Images/image1.jpg', cv2.IMREAD_COLOR)

#Suppose we want to create a polygon on the image
pts = np.array([[12,3],[14,23],[122,231],[256,345],[302,401],[315,445]], np.int32) #Creates an ndarray consisting of list of points in the polygon

In [68]:
cv2.polylines(image, [pts], True, (0,255,255), 5) 
#cv.polylines(image_obj, points_array, isconnect(asks whether to connect the final point to the initial point or not), color_value, linewidth)

array([[[ 49,  76,  73],
        [ 40,  67,  64],
        [ 30,  57,  53],
        ...,
        [245, 252, 255],
        [239, 248, 252],
        [233, 242, 246]],

       [[ 43,  70,  67],
        [ 36,  63,  60],
        [ 29,  56,  53],
        ...,
        [244, 255, 255],
        [240, 251, 255],
        [223, 235, 239]],

       [[ 39,  67,  67],
        [ 37,  66,  63],
        [ 34,  63,  60],
        ...,
        [194, 212, 213],
        [209, 228, 231],
        [204, 223, 226]],

       ...,

       [[ 57,  63,  68],
        [ 54,  60,  65],
        [ 50,  56,  61],
        ...,
        [138, 137, 139],
        [118, 120, 120],
        [113, 115, 115]],

       [[ 57,  63,  68],
        [ 55,  61,  66],
        [ 52,  58,  63],
        ...,
        [144, 143, 145],
        [127, 129, 129],
        [123, 125, 125]],

       [[ 58,  64,  69],
        [ 57,  63,  68],
        [ 55,  61,  66],
        ...,
        [145, 144, 146],
        [139, 141, 141],
        [142, 144, 144]]

In [69]:
#Displaying the image
cv2.imshow('Image Window', image)
cv2.waitKey(0)
cv2.destroyAllWindows()