In [1]:
import cv2
import numpy as np

In [9]:
#Loading an image
image = cv2.imread('Images\image1.jpg', -1)

In [3]:
#Finding color value of a certain pixel
px = image[100,250]
px

array([166, 200, 194], dtype=uint8)

In [4]:
#We can assign the image new color values
image[100,250] = np.array([255,255,255])
px = image[100,250]
px

array([255, 255, 255], dtype=uint8)

In [7]:
#Now if we want to apply the image color assignment to a particular set of image pixels, we have:

image[100:250, 100:250] = np.array([255,255,255])
roi = image[100:250, 100:250] #Selects the pixel values between 100-250 range from both x and y
print(roi)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [8]:
#Displaying the image
cv2.imshow('Image Window', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#We can also use the image component from the image and use it somewhere else in the image, to do that:
take_image = image[212:362, 212:362]
image[100:250, 100:250] = take_image

In [11]:
#Displaying the image
cv2.imshow('Image Window', image)
cv2.waitKey(0)
cv2.destroyAllWindows()